### ISSUE TITLE
create plots daily min/max temp for last 10 years

### ISSUE THREAD

**Issue by Ajay-Vijayakumar** [CMSC6950/GDD-Project--Team1#2]
input file: plot_input.csv

**Comment by demarey-baker** [comment]
This is done check it out!

**Comment by dw-wang** [comment]
Hi, this code seems to have something wrong! I tried to run it but got an error!

**Comment by demarey-baker** [comment]
What error are u getting?

**Comment by demarey-baker** [comment]
I think it has to do with your newly added code and makefile..try to run the previous version and see if u did nothing wrong while integrating your new code

**Comment by demarey-baker** [comment]
U basically changed all the code that was there already so thats why its throwing error I will have to look through your code and match it back..

**Comment by dw-wang** [comment]
Sorry, I didn't notice that, let me check again!

**Comment by demarey-baker** [comment]
Yes bro no worries I will just modify it to match yours.. me and ajay agreed on a format for the files so thats why..i will just modify based on what u did..

**Comment by dw-wang** [comment]
Hi this is the error information I got, I think it's some pandas function error in your file:

``Plotting min-max values
python3 min_max_plot.py
Traceback (most recent call last):
  File "min_max_plot.py", line 72, in <module>
    Data = pd.read_csv(filepath+file, encoding = 'utf-8')
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 285, in _read
    return parser.read()
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 747, in read
    ret = self._engine.read(nrows)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1197, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 766, in pandas.parser.TextReader.read (pandas/parser.c:7988)
  File "pandas/parser.pyx", line 788, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:8244)
  File "pandas/parser.pyx", line 842, in pandas.parser.TextReader._read_rows (pandas/parser.c:8970)
  File "pandas/parser.pyx", line 829, in pandas.parser.TextReader._tokenize_rows (pandas/parser.c:8838)
  File "pandas/parser.pyx", line 1833, in pandas.parser.raise_parser_error (pandas/parser.c:22649)
pandas.parser.CParserError: Error tokenizing data. C error: Expected 2 fields in line 25, saw 27

**Comment by demarey-baker** [comment]
Yes, i expect that.. your saving the files different than how I did thats why. Thats why its not parsing corectly. I will fix it to match yours tonight. 
This is because me and ajay agreed on a specific format so i was working based on that..

**Comment by dw-wang** [comment]
Ok, thanks!

**Comment by dw-wang** [comment]
What is your agreed format? I can also change my code to match yours.

**Comment by dw-wang** [comment]
I think your get_weather_data function is not correct, you should specify index_col=0. I didn't change that, please take a look.
